config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :user_skills
  resources :user_projects
  resources :projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/login", to:"login#new"
  post "/login", to:"login#create"
  post "/logout", to:"login#destroy"

  root "login#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :skill
    has_many :user_projects

    validates :title, :pay, :skill_id, presence: true

end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :user_skills
    has_many :projects

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_projects
    has_many :user_skills
    has_many :skills, through: :user_skills
    has_many :projects, through: :user_projects

    validates :first_name, :last_name, :email, :money, presence: true
    validates :email, uniqueness: true
    validates :money, numericality: true

    def full_name

        "#{@user.first_name}  #{@user.last_name}"

    end
end

app/models/user_project.rb
class UserProject < ApplicationRecord
    belongs_to :project
    belongs_to :user

    validates :user_id, :project_id, presence: true

    # validates :skill_match

# def skill_match
#     if !@user.skills.include? (@project.skill)
#         self.errors.add(  )
#     end
# end




end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
    belongs_to :user
    belongs_to :skill

    validates :user_id, :skill_id, :level, presence: true
    validates :level, numericality: {greater_than: 0, less_than: 11} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    def new
      # gets the form
    end
  
    def create
        # check the information inside the form
        @user = User.find_by(email: params[:email])
        if @user #&& @user.authenticate(params[:email])
          session[:user_id] = @user.id
          redirect_to (@user)
        else
          flash[:message] = "Incorrect Email"
          redirect_to "/login"
        end
      end
    
      def destroy
       logout
       redirect_to("/login")
      end
   
  
  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :find_project, only: [:show]

    def index
        @projects = Project.all
    end

    def show

    end

    def new
        @project = Project.new
    end

    def edit

    end

    def create
        @project = Project.create(project_params)
        redirect_to @project
    end

    def update

    end

    def destroy

    end

    private

    def find_project
        @project = Project.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:title, :pay, :skill_id)
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    before_action :current_skill, only: [:show]

    def index 
        @skills = Skill.all
    end

    def show
    end

    def new
        @skill = Skill.new
    end

    def create 
        @skill = Skill.create(skill_params)
        redirect_to skill_path(@skill)
    end


    def update
        @skill = Skill.update(skill_params)
        redirect_to skill_path(@skill)
    end


    private

    def skill_params
        params.require(:skill).permit(:name)
    end

    def current_skill
        @skill = Skill.find(params[:id])
    end
    
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController



    def index 
        @user_projects = UserProject.all 
    end

    def show

    end

    def new
        @userproject = UserProject.new
    end

    def create 
        
    end

    def edit

    end

    def update

    end

    def destroy

    end

end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController
    before_action :current_us, only: [:show]

    def index 
        @user_skills = UserSkill.all
    end

    def show

    end

    def new
        @user_skill = UserSkill.new
    end

    def create 
        @user_skill = UserSkill.create(us_params)
        redirect_to @user_skill.user
    end

  private

    def us_params
        params.require(:user_skill).permit(:user_id, :skill_id, :level)
    end

    def current_us
        @user_skill = UserSkill.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
    end
    
    def show
    end

    def new
        @user = User.new
    end

    def create 
        @user = User.create(user_params)
        if user.valid?
            redirect_to @user
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
    end

    def update
        @user.update(user_params)
        if user.valid?
            redirect_to user_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to edit_user_path(@user)
        end
    end

    def destroy
        @user.destroy
        redirect_to new_users_path 
    end


    private

    def current_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :money)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/user_skills_helper.rb
module UserSkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkillUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/new.html.erb
<h2>Please Login to SkillUp</h2>

<% if flash[:message] %>
  <p><%= flash[:message] %></p>
<% end %>

<div class="d-flex" style="vertical-align: middle;padding-top: 5%;">
  <div class="container border border-dark rounded">
    <div class="row justify-content-center">
      <div class="col-4">
        <%= form_tag "/login" do %>
            <div class="form-group">
                    <%= label_tag :Email%>
                    <%= email_field_tag :email, nil, {class: "form-control"} %>
      </div>

          <%= submit_tag "Login", class:"btn-btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f|%>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :pay %>
<%= f.text_field :pay %>

<%= f.label :skill_id %>
<%= f.text_field :skill_id %>

<%= f.submit "Create" %>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project  %>

app/views/projects/index.html.erb
<h1>Available Projects</h1>

<ul>
    <% @projects.each do |project| %>
        <li>
            <%=" Project: #{project.title} "%>
            <p><%=" Payout: #{project.pay}"%></p>
            <p><%=" Required Skill: #{project.skill.name}"%></P>
            <%= button_to "Work on this project", new_user_project_path, :method => "get" %>
        </li>
    <% end %>
</ul>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project  %>

app/views/projects/show.html.erb
<h1>More Project Info</h1>
    <p>
        <%= @project.name %>
    </p>

    <p>
        <%= @project.pay %>
    </p>

    <p>
        <%= @project.skill_id.name %>
    </p>

    <p>
        <%= link_to 'Back', projects_path %>
    </p>

app/views/skills/_form.erb
<%= form_for @skills do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit %>

<% end %>

app/views/skills/edit.erb
<h1>Edit Skill</h1>
<%= render 'form' %>

app/views/skills/index.erb
<h1>All The Skills</h1>

<% @skills.each do |skill| %>
    <%= skill.name %>
<% end %>

app/views/skills/index.html.erb
<h1>Skill Sets</h1>

<ul>
    <% @skills.each do |skill| %>
        <li>
            <%="#{skill.name}"%>
        </li>
    <% end %>
</ul>

app/views/skills/new.erb
<h1>Enter New Skill</h1>
<%= render 'form' %>

app/views/user_projects/_form.html.erb
<%= form_for(@userproject) do |f|%>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :pay %>
<%= f.text_field :pay %>

<%= f.label :skill_id %>
<%= f.text_field :skill_id %>

<%= f.submit "Add" %>

<% end %>

app/views/user_projects/index.erb
<h1>All User Projects</h1>

app/views/user_projects/show.erb
<h1>User Project Show Page</h1>

app/views/user_skills/index.erb
<h1>User Skills Index</h1>

app/views/user_skills/show.erb
<h1>This User's Skills</h1>

app/views/users/_form.erb
<ul>
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <li> <%= error %> </li>
<% end %>
</ul>
<<<<<<< HEAD

<%= form_for @user do |f| %>

    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
=======

<%= form_for(@user) do |f| %>
>>>>>>> e13e6fcfe5708c6d8bd3d3aac65677f80052926a

    <%= f.label :full_name %>
    <%= f.text_field :full_name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :level %>
    <%= f.text_field :level %>

    <%= f.submit %>
<% end %>

app/views/users/edit.erb
<h1>Update Your Information</h1>

<%= render 'form', user: @user %>

app/views/users/index.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= "Name: #{user.name}" %></li>
      <%= link_to "Users Info", user %>
  <% end %>
</ul>

<%= link_to "New User?", new_user_path %>

app/views/users/new.erb
<h1>Become a SkillUp Freelancer!</h1>

<%= render 'form', user: @user %>

app/views/users/show.erb
<h1> Welcome Back, <%= "#{@user.full_name}"%></h1>



<% @user.user_skills.each do |us| %>
    <ul>
        <li>
            <%= us.skill.name %> 
        <p>
            <%= us.level %>
        </p>
    </ul>
<% end %>

<p>
<%= link_to "Take on a new project!", new_user_projects_path %>
</p>

<% @user.user_projects.each do |up| %>
    <% if up.status < 100 %>
        <%= up.project.title %>
        <%= up.status %>
        <%= up.project.pay %>
    <% end %>
<% end %>

<% @user.user_projects.each do |up| %>
    <% if up.status == 100 %>
        <%= up.project.title %>
        <%= up.project.pay %>
    <% end %>
<% end %>